import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_feather_icons/flutter_feather_icons.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_iconly/flutter_iconly.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:ultimate_bundle/helpers/constants.dart';
import 'package:ultimate_bundle/src/lestate/src/helpers/constants.dart';
import 'package:ultimate_bundle/src/lestate/src/models/estate_model.dart';
import 'package:ultimate_bundle/src/lestate/src/widgets/custom_app_bar.dart';
import 'package:ultimate_bundle/src/lestate/src/widgets/custom_elevated_button.dart';

part 'screens/summary_screen.dart';
part 'widgets/build_estate_list_tile.dart';
part 'widgets/build_payment_method.dart';
part 'widgets/build_check_in_out_card.dart';
part 'widgets/build_transaction_detail.dart';
