import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_feather_icons/flutter_feather_icons.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:ultimate_bundle/helpers/constants.dart';
import 'package:ultimate_bundle/src/belila/src/helpers/colors.dart';
import 'package:ultimate_bundle/src/belila/src/helpers/constants.dart';
import 'package:ultimate_bundle/src/belila/src/helpers/screens.dart';
import 'package:ultimate_bundle/src/belila/src/helpers/toast.dart';
import 'package:ultimate_bundle/src/belila/src/models/user_model.dart';
import 'package:ultimate_bundle/src/belila/src/widgets/custom_app_bar.dart';
import 'package:ultimate_bundle/src/belila/src/widgets/custom_elevated_button.dart';
import 'package:ultimate_bundle/src/belila/src/widgets/custom_text_form_field.dart';

part 'screens/profile_edit_screen.dart';
part 'widgets/build_change_profile_photo.dart';
part 'widgets/photo_modal_bottom_sheet.dart';
